# Generated by Django 5.2 on 2025-05-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_blog_content_alter_blog_image'),
        ('blogapp', '0010_alter_category_slug_alter_tag_slug'),
    ]

    operations = [
    ]
